// Generated by tools/randomizer_voice_assets.py.
#include "seq_macros.inc"

.section .rodata
.align 0

sequence_start:
seq_setmutebhv 0x60
seq_setmutescale 0
seq_setvol 127
seq_settempo 120
seq_initchannels 0x1
seq_startchannel 0, .voice_channel
.seq_loop:
seq_delay 20000
seq_jump .seq_loop

.voice_channel:
chan_largenoteson
chan_setinstr 0
chan_setnotepriority 14
chan_setval 0
chan_iowriteval 5
chan_setmutebhv 0x0
chan_stereoheadseteffects 1
chan_setdyntable .voice_table
.voice_wait:
chan_delay1
chan_ioreadval 0
chan_bltz .voice_wait
.voice_start:
chan_freelayer 0
chan_freelayer 1
chan_freelayer 2
chan_setval 0
chan_iowriteval 5
chan_setreverb 0
chan_setpan 64
chan_setpanmix 127
chan_ioreadval 4
chan_dyncall
.voice_poll:
chan_delay1
chan_ioreadval 0
chan_bltz .voice_skip
  chan_beqz .voice_stop
  chan_unreservenotes
  chan_jump .voice_start
.voice_skip:
chan_testlayerfinished 0
chan_beqz .voice_poll
chan_unreservenotes
chan_jump .voice_wait
.voice_stop:
chan_freelayer 0
chan_freelayer 1
chan_freelayer 2
chan_unreservenotes
chan_jump .voice_wait

.voice_table:
sound_ref .sound_rando_voice_000
sound_ref .sound_rando_voice_001
sound_ref .sound_rando_voice_002
sound_ref .sound_rando_voice_003
sound_ref .sound_rando_voice_004
sound_ref .sound_rando_voice_005
sound_ref .sound_rando_voice_006
sound_ref .sound_rando_voice_007
sound_ref .sound_rando_voice_008
sound_ref .sound_rando_voice_009
sound_ref .sound_rando_voice_010
sound_ref .sound_rando_voice_011
sound_ref .sound_rando_voice_012
sound_ref .sound_rando_voice_013
sound_ref .sound_rando_voice_014
sound_ref .sound_rando_voice_015
sound_ref .sound_rando_voice_016
sound_ref .sound_rando_voice_017
sound_ref .sound_rando_voice_018
sound_ref .sound_rando_voice_019
sound_ref .sound_rando_voice_020
sound_ref .sound_rando_voice_021
sound_ref .sound_rando_voice_022
sound_ref .sound_rando_voice_023
sound_ref .sound_rando_voice_024
sound_ref .sound_rando_voice_025
sound_ref .sound_rando_voice_026
sound_ref .sound_rando_voice_027
sound_ref .sound_rando_voice_028
sound_ref .sound_rando_voice_029
sound_ref .sound_rando_voice_030
sound_ref .sound_rando_voice_031
sound_ref .sound_rando_voice_032
sound_ref .sound_rando_voice_033
sound_ref .sound_rando_voice_034
sound_ref .sound_rando_voice_035
sound_ref .sound_rando_voice_036
sound_ref .sound_rando_voice_037
sound_ref .sound_rando_voice_038
sound_ref .sound_rando_voice_039
sound_ref .sound_rando_voice_040
sound_ref .sound_rando_voice_041
sound_ref .sound_rando_voice_042
sound_ref .sound_rando_voice_043
sound_ref .sound_rando_voice_044
sound_ref .sound_rando_voice_045
sound_ref .sound_rando_voice_046
sound_ref .sound_rando_voice_047
sound_ref .sound_rando_voice_048
sound_ref .sound_rando_voice_049
sound_ref .sound_rando_voice_050
sound_ref .sound_rando_voice_051
sound_ref .sound_rando_voice_052
sound_ref .sound_rando_voice_053
sound_ref .sound_rando_voice_054
sound_ref .sound_rando_voice_055
sound_ref .sound_rando_voice_056
sound_ref .sound_rando_voice_057
sound_ref .sound_rando_voice_058
sound_ref .sound_rando_voice_059
sound_ref .sound_rando_voice_060
sound_ref .sound_rando_voice_061
sound_ref .sound_rando_voice_062
sound_ref .sound_rando_voice_063
sound_ref .sound_rando_voice_064
sound_ref .sound_rando_voice_065
sound_ref .sound_rando_voice_066
sound_ref .sound_rando_voice_067
sound_ref .sound_rando_voice_068
sound_ref .sound_rando_voice_069
sound_ref .sound_rando_voice_070
sound_ref .sound_rando_voice_071
sound_ref .sound_rando_voice_072
sound_ref .sound_rando_voice_073
sound_ref .sound_rando_voice_074
sound_ref .sound_rando_voice_075
sound_ref .sound_rando_voice_076
sound_ref .sound_rando_voice_077
sound_ref .sound_rando_voice_078
sound_ref .sound_rando_voice_079
sound_ref .sound_rando_voice_080
sound_ref .sound_rando_voice_081
sound_ref .sound_rando_voice_082
sound_ref .sound_rando_voice_083
sound_ref .sound_rando_voice_084
sound_ref .sound_rando_voice_085
sound_ref .sound_rando_voice_086
sound_ref .sound_rando_voice_087
sound_ref .sound_rando_voice_088
sound_ref .sound_rando_voice_089
sound_ref .sound_rando_voice_090
sound_ref .sound_rando_voice_091
sound_ref .sound_rando_voice_092
sound_ref .sound_rando_voice_093
sound_ref .sound_rando_voice_094
sound_ref .sound_rando_voice_095
sound_ref .sound_rando_voice_096
sound_ref .sound_rando_voice_097
sound_ref .sound_rando_voice_098
sound_ref .sound_rando_voice_099
sound_ref .sound_rando_voice_100
sound_ref .sound_rando_voice_101
sound_ref .sound_rando_voice_102
sound_ref .sound_rando_voice_103
sound_ref .sound_rando_voice_104
sound_ref .sound_rando_voice_105
sound_ref .sound_rando_voice_106
sound_ref .sound_rando_voice_107
sound_ref .sound_rando_voice_108
sound_ref .sound_rando_voice_109
sound_ref .sound_rando_voice_110
sound_ref .sound_rando_voice_111
sound_ref .sound_rando_voice_112
sound_ref .sound_rando_voice_113
sound_ref .sound_rando_voice_114
sound_ref .sound_rando_voice_115
sound_ref .sound_rando_voice_116
sound_ref .sound_rando_voice_117
sound_ref .sound_rando_voice_118
sound_ref .sound_rando_voice_119

.sound_rando_voice_000:
chan_setbank 0
chan_setinstr 0
chan_setlayer 0, .layer_rando_voice_000
chan_end

.layer_rando_voice_000:
layer_note1_long 39, 146, 127
layer_end

.sound_rando_voice_001:
chan_setbank 0
chan_setinstr 1
chan_setlayer 0, .layer_rando_voice_001
chan_end

.layer_rando_voice_001:
layer_note1_long 39, 134, 127
layer_end

.sound_rando_voice_002:
chan_setbank 0
chan_setinstr 2
chan_setlayer 0, .layer_rando_voice_002
chan_end

.layer_rando_voice_002:
layer_note1_long 39, 130, 127
layer_end

.sound_rando_voice_003:
chan_setbank 0
chan_setinstr 3
chan_setlayer 0, .layer_rando_voice_003
chan_end

.layer_rando_voice_003:
layer_note1_long 39, 240, 127
layer_end

.sound_rando_voice_004:
chan_setbank 0
chan_setinstr 4
chan_setlayer 0, .layer_rando_voice_004
chan_end

.layer_rando_voice_004:
layer_note1_long 39, 120, 127
layer_end

.sound_rando_voice_005:
chan_setbank 0
chan_setinstr 5
chan_setlayer 0, .layer_rando_voice_005
chan_end

.layer_rando_voice_005:
layer_note1_long 39, 126, 127
layer_end

.sound_rando_voice_006:
chan_setbank 0
chan_setinstr 6
chan_setlayer 0, .layer_rando_voice_006
chan_end

.layer_rando_voice_006:
layer_note1_long 39, 228, 127
layer_end

.sound_rando_voice_007:
chan_setbank 0
chan_setinstr 7
chan_setlayer 0, .layer_rando_voice_007
chan_end

.layer_rando_voice_007:
layer_note1_long 39, 116, 127
layer_end

.sound_rando_voice_008:
chan_setbank 1
chan_setinstr 0
chan_setlayer 0, .layer_rando_voice_008
chan_end

.layer_rando_voice_008:
layer_note1_long 39, 124, 127
layer_end

.sound_rando_voice_009:
chan_setbank 1
chan_setinstr 1
chan_setlayer 0, .layer_rando_voice_009
chan_end

.layer_rando_voice_009:
layer_note1_long 39, 122, 127
layer_end

.sound_rando_voice_010:
chan_setbank 1
chan_setinstr 2
chan_setlayer 0, .layer_rando_voice_010
chan_end

.layer_rando_voice_010:
layer_note1_long 39, 216, 127
layer_end

.sound_rando_voice_011:
chan_setbank 1
chan_setinstr 3
chan_setlayer 0, .layer_rando_voice_011
chan_end

.layer_rando_voice_011:
layer_note1_long 39, 136, 127
layer_end

.sound_rando_voice_012:
chan_setbank 1
chan_setinstr 4
chan_setlayer 0, .layer_rando_voice_012
chan_end

.layer_rando_voice_012:
layer_note1_long 39, 118, 127
layer_end

.sound_rando_voice_013:
chan_setbank 1
chan_setinstr 5
chan_setlayer 0, .layer_rando_voice_013
chan_end

.layer_rando_voice_013:
layer_note1_long 39, 192, 127
layer_end

.sound_rando_voice_014:
chan_setbank 1
chan_setinstr 6
chan_setlayer 0, .layer_rando_voice_014
chan_end

.layer_rando_voice_014:
layer_note1_long 39, 126, 127
layer_end

.sound_rando_voice_015:
chan_setbank 1
chan_setinstr 7
chan_setlayer 0, .layer_rando_voice_015
chan_end

.layer_rando_voice_015:
layer_note1_long 39, 126, 127
layer_end

.sound_rando_voice_016:
chan_setbank 2
chan_setinstr 0
chan_setlayer 0, .layer_rando_voice_016
chan_end

.layer_rando_voice_016:
layer_note1_long 39, 128, 127
layer_end

.sound_rando_voice_017:
chan_setbank 2
chan_setinstr 1
chan_setlayer 0, .layer_rando_voice_017
chan_end

.layer_rando_voice_017:
layer_note1_long 39, 218, 127
layer_end

.sound_rando_voice_018:
chan_setbank 2
chan_setinstr 2
chan_setlayer 0, .layer_rando_voice_018
chan_end

.layer_rando_voice_018:
layer_note1_long 39, 120, 127
layer_end

.sound_rando_voice_019:
chan_setbank 2
chan_setinstr 3
chan_setlayer 0, .layer_rando_voice_019
chan_end

.layer_rando_voice_019:
layer_note1_long 39, 106, 127
layer_end

.sound_rando_voice_020:
chan_setbank 2
chan_setinstr 4
chan_setlayer 0, .layer_rando_voice_020
chan_end

.layer_rando_voice_020:
layer_note1_long 39, 198, 127
layer_end

.sound_rando_voice_021:
chan_setbank 2
chan_setinstr 5
chan_setlayer 0, .layer_rando_voice_021
chan_end

.layer_rando_voice_021:
layer_note1_long 39, 110, 127
layer_end

.sound_rando_voice_022:
chan_setbank 2
chan_setinstr 6
chan_setlayer 0, .layer_rando_voice_022
chan_end

.layer_rando_voice_022:
layer_note1_long 39, 110, 127
layer_end

.sound_rando_voice_023:
chan_setbank 2
chan_setinstr 7
chan_setlayer 0, .layer_rando_voice_023
chan_end

.layer_rando_voice_023:
layer_note1_long 39, 110, 127
layer_end

.sound_rando_voice_024:
chan_setbank 3
chan_setinstr 0
chan_setlayer 0, .layer_rando_voice_024
chan_end

.layer_rando_voice_024:
layer_note1_long 39, 248, 127
layer_end

.sound_rando_voice_025:
chan_setbank 3
chan_setinstr 1
chan_setlayer 0, .layer_rando_voice_025
chan_end

.layer_rando_voice_025:
layer_note1_long 39, 130, 127
layer_end

.sound_rando_voice_026:
chan_setbank 3
chan_setinstr 2
chan_setlayer 0, .layer_rando_voice_026
chan_end

.layer_rando_voice_026:
layer_note1_long 39, 110, 127
layer_end

.sound_rando_voice_027:
chan_setbank 3
chan_setinstr 3
chan_setlayer 0, .layer_rando_voice_027
chan_end

.layer_rando_voice_027:
layer_note1_long 39, 200, 127
layer_end

.sound_rando_voice_028:
chan_setbank 3
chan_setinstr 4
chan_setlayer 0, .layer_rando_voice_028
chan_end

.layer_rando_voice_028:
layer_note1_long 39, 108, 127
layer_end

.sound_rando_voice_029:
chan_setbank 3
chan_setinstr 5
chan_setlayer 0, .layer_rando_voice_029
chan_end

.layer_rando_voice_029:
layer_note1_long 39, 144, 127
layer_end

.sound_rando_voice_030:
chan_setbank 3
chan_setinstr 6
chan_setlayer 0, .layer_rando_voice_030
chan_end

.layer_rando_voice_030:
layer_note1_long 39, 132, 127
layer_end

.sound_rando_voice_031:
chan_setbank 3
chan_setinstr 7
chan_setlayer 0, .layer_rando_voice_031
chan_end

.layer_rando_voice_031:
layer_note1_long 39, 202, 127
layer_end

.sound_rando_voice_032:
chan_setbank 4
chan_setinstr 0
chan_setlayer 0, .layer_rando_voice_032
chan_end

.layer_rando_voice_032:
layer_note1_long 39, 106, 127
layer_end

.sound_rando_voice_033:
chan_setbank 4
chan_setinstr 1
chan_setlayer 0, .layer_rando_voice_033
chan_end

.layer_rando_voice_033:
layer_note1_long 39, 126, 127
layer_end

.sound_rando_voice_034:
chan_setbank 4
chan_setinstr 2
chan_setlayer 0, .layer_rando_voice_034
chan_end

.layer_rando_voice_034:
layer_note1_long 39, 190, 127
layer_end

.sound_rando_voice_035:
chan_setbank 4
chan_setinstr 3
chan_setlayer 0, .layer_rando_voice_035
chan_end

.layer_rando_voice_035:
layer_note1_long 39, 132, 127
layer_end

.sound_rando_voice_036:
chan_setbank 4
chan_setinstr 4
chan_setlayer 0, .layer_rando_voice_036
chan_end

.layer_rando_voice_036:
layer_note1_long 39, 226, 127
layer_end

.sound_rando_voice_037:
chan_setbank 4
chan_setinstr 5
chan_setlayer 0, .layer_rando_voice_037
chan_end

.layer_rando_voice_037:
layer_note1_long 39, 138, 127
layer_end

.sound_rando_voice_038:
chan_setbank 4
chan_setinstr 6
chan_setlayer 0, .layer_rando_voice_038
chan_end

.layer_rando_voice_038:
layer_note1_long 39, 140, 127
layer_end

.sound_rando_voice_039:
chan_setbank 4
chan_setinstr 7
chan_setlayer 0, .layer_rando_voice_039
chan_end

.layer_rando_voice_039:
layer_note1_long 39, 140, 127
layer_end

.sound_rando_voice_040:
chan_setbank 5
chan_setinstr 0
chan_setlayer 0, .layer_rando_voice_040
chan_end

.layer_rando_voice_040:
layer_note1_long 39, 120, 127
layer_end

.sound_rando_voice_041:
chan_setbank 5
chan_setinstr 1
chan_setlayer 0, .layer_rando_voice_041
chan_end

.layer_rando_voice_041:
layer_note1_long 39, 202, 127
layer_end

.sound_rando_voice_042:
chan_setbank 5
chan_setinstr 2
chan_setlayer 0, .layer_rando_voice_042
chan_end

.layer_rando_voice_042:
layer_note1_long 39, 104, 127
layer_end

.sound_rando_voice_043:
chan_setbank 5
chan_setinstr 3
chan_setlayer 0, .layer_rando_voice_043
chan_end

.layer_rando_voice_043:
layer_note1_long 39, 94, 127
layer_end

.sound_rando_voice_044:
chan_setbank 5
chan_setinstr 4
chan_setlayer 0, .layer_rando_voice_044
chan_end

.layer_rando_voice_044:
layer_note1_long 39, 252, 127
layer_end

.sound_rando_voice_045:
chan_setbank 5
chan_setinstr 5
chan_setlayer 0, .layer_rando_voice_045
chan_end

.layer_rando_voice_045:
layer_note1_long 39, 108, 127
layer_end

.sound_rando_voice_046:
chan_setbank 5
chan_setinstr 6
chan_setlayer 0, .layer_rando_voice_046
chan_end

.layer_rando_voice_046:
layer_note1_long 39, 138, 127
layer_end

.sound_rando_voice_047:
chan_setbank 5
chan_setinstr 7
chan_setlayer 0, .layer_rando_voice_047
chan_end

.layer_rando_voice_047:
layer_note1_long 39, 144, 127
layer_end

.sound_rando_voice_048:
chan_setbank 6
chan_setinstr 0
chan_setlayer 0, .layer_rando_voice_048
chan_end

.layer_rando_voice_048:
layer_note1_long 39, 200, 127
layer_end

.sound_rando_voice_049:
chan_setbank 6
chan_setinstr 1
chan_setlayer 0, .layer_rando_voice_049
chan_end

.layer_rando_voice_049:
layer_note1_long 39, 134, 127
layer_end

.sound_rando_voice_050:
chan_setbank 6
chan_setinstr 2
chan_setlayer 0, .layer_rando_voice_050
chan_end

.layer_rando_voice_050:
layer_note1_long 39, 128, 127
layer_end

.sound_rando_voice_051:
chan_setbank 6
chan_setinstr 3
chan_setlayer 0, .layer_rando_voice_051
chan_end

.layer_rando_voice_051:
layer_note1_long 39, 132, 127
layer_end

.sound_rando_voice_052:
chan_setbank 6
chan_setinstr 4
chan_setlayer 0, .layer_rando_voice_052
chan_end

.layer_rando_voice_052:
layer_note1_long 39, 148, 127
layer_end

.sound_rando_voice_053:
chan_setbank 6
chan_setinstr 5
chan_setlayer 0, .layer_rando_voice_053
chan_end

.layer_rando_voice_053:
layer_note1_long 39, 244, 127
layer_end

.sound_rando_voice_054:
chan_setbank 6
chan_setinstr 6
chan_setlayer 0, .layer_rando_voice_054
chan_end

.layer_rando_voice_054:
layer_note1_long 39, 94, 127
layer_end

.sound_rando_voice_055:
chan_setbank 6
chan_setinstr 7
chan_setlayer 0, .layer_rando_voice_055
chan_end

.layer_rando_voice_055:
layer_note1_long 39, 208, 127
layer_end

.sound_rando_voice_056:
chan_setbank 7
chan_setinstr 0
chan_setlayer 0, .layer_rando_voice_056
chan_end

.layer_rando_voice_056:
layer_note1_long 39, 108, 127
layer_end

.sound_rando_voice_057:
chan_setbank 7
chan_setinstr 1
chan_setlayer 0, .layer_rando_voice_057
chan_end

.layer_rando_voice_057:
layer_note1_long 39, 106, 127
layer_end

.sound_rando_voice_058:
chan_setbank 7
chan_setinstr 2
chan_setlayer 0, .layer_rando_voice_058
chan_end

.layer_rando_voice_058:
layer_note1_long 39, 228, 127
layer_end

.sound_rando_voice_059:
chan_setbank 7
chan_setinstr 3
chan_setlayer 0, .layer_rando_voice_059
chan_end

.layer_rando_voice_059:
layer_note1_long 39, 106, 127
layer_end

.sound_rando_voice_060:
chan_setbank 7
chan_setinstr 4
chan_setlayer 0, .layer_rando_voice_060
chan_end

.layer_rando_voice_060:
layer_note1_long 39, 112, 127
layer_end

.sound_rando_voice_061:
chan_setbank 7
chan_setinstr 5
chan_setlayer 0, .layer_rando_voice_061
chan_end

.layer_rando_voice_061:
layer_note1_long 39, 96, 127
layer_end

.sound_rando_voice_062:
chan_setbank 7
chan_setinstr 6
chan_setlayer 0, .layer_rando_voice_062
chan_end

.layer_rando_voice_062:
layer_note1_long 39, 204, 127
layer_end

.sound_rando_voice_063:
chan_setbank 7
chan_setinstr 7
chan_setlayer 0, .layer_rando_voice_063
chan_end

.layer_rando_voice_063:
layer_note1_long 39, 112, 127
layer_end

.sound_rando_voice_064:
chan_setbank 8
chan_setinstr 0
chan_setlayer 0, .layer_rando_voice_064
chan_end

.layer_rando_voice_064:
layer_note1_long 39, 100, 127
layer_end

.sound_rando_voice_065:
chan_setbank 8
chan_setinstr 1
chan_setlayer 0, .layer_rando_voice_065
chan_end

.layer_rando_voice_065:
layer_note1_long 39, 100, 127
layer_end

.sound_rando_voice_066:
chan_setbank 8
chan_setinstr 2
chan_setlayer 0, .layer_rando_voice_066
chan_end

.layer_rando_voice_066:
layer_note1_long 39, 130, 127
layer_end

.sound_rando_voice_067:
chan_setbank 8
chan_setinstr 3
chan_setlayer 0, .layer_rando_voice_067
chan_end

.layer_rando_voice_067:
layer_note1_long 39, 230, 127
layer_end

.sound_rando_voice_068:
chan_setbank 8
chan_setinstr 4
chan_setlayer 0, .layer_rando_voice_068
chan_end

.layer_rando_voice_068:
layer_note1_long 39, 90, 127
layer_end

.sound_rando_voice_069:
chan_setbank 8
chan_setinstr 5
chan_setlayer 0, .layer_rando_voice_069
chan_end

.layer_rando_voice_069:
layer_note1_long 39, 200, 127
layer_end

.sound_rando_voice_070:
chan_setbank 8
chan_setinstr 6
chan_setlayer 0, .layer_rando_voice_070
chan_end

.layer_rando_voice_070:
layer_note1_long 39, 118, 127
layer_end

.sound_rando_voice_071:
chan_setbank 8
chan_setinstr 7
chan_setlayer 0, .layer_rando_voice_071
chan_end

.layer_rando_voice_071:
layer_note1_long 39, 98, 127
layer_end

.sound_rando_voice_072:
chan_setbank 9
chan_setinstr 0
chan_setlayer 0, .layer_rando_voice_072
chan_end

.layer_rando_voice_072:
layer_note1_long 39, 148, 127
layer_end

.sound_rando_voice_073:
chan_setbank 9
chan_setinstr 1
chan_setlayer 0, .layer_rando_voice_073
chan_end

.layer_rando_voice_073:
layer_note1_long 39, 140, 127
layer_end

.sound_rando_voice_074:
chan_setbank 9
chan_setinstr 2
chan_setlayer 0, .layer_rando_voice_074
chan_end

.layer_rando_voice_074:
layer_note1_long 39, 216, 127
layer_end

.sound_rando_voice_075:
chan_setbank 9
chan_setinstr 3
chan_setlayer 0, .layer_rando_voice_075
chan_end

.layer_rando_voice_075:
layer_note1_long 39, 124, 127
layer_end

.sound_rando_voice_076:
chan_setbank 9
chan_setinstr 4
chan_setlayer 0, .layer_rando_voice_076
chan_end

.layer_rando_voice_076:
layer_note1_long 39, 192, 127
layer_end

.sound_rando_voice_077:
chan_setbank 9
chan_setinstr 5
chan_setlayer 0, .layer_rando_voice_077
chan_end

.layer_rando_voice_077:
layer_note1_long 39, 98, 127
layer_end

.sound_rando_voice_078:
chan_setbank 9
chan_setinstr 6
chan_setlayer 0, .layer_rando_voice_078
chan_end

.layer_rando_voice_078:
layer_note1_long 39, 130, 127
layer_end

.sound_rando_voice_079:
chan_setbank 9
chan_setinstr 7
chan_setlayer 0, .layer_rando_voice_079
chan_end

.layer_rando_voice_079:
layer_note1_long 39, 260, 127
layer_end

.sound_rando_voice_080:
chan_setbank 10
chan_setinstr 0
chan_setlayer 0, .layer_rando_voice_080
chan_end

.layer_rando_voice_080:
layer_note1_long 39, 122, 127
layer_end

.sound_rando_voice_081:
chan_setbank 10
chan_setinstr 1
chan_setlayer 0, .layer_rando_voice_081
chan_end

.layer_rando_voice_081:
layer_note1_long 39, 134, 127
layer_end

.sound_rando_voice_082:
chan_setbank 10
chan_setinstr 2
chan_setlayer 0, .layer_rando_voice_082
chan_end

.layer_rando_voice_082:
layer_note1_long 39, 134, 127
layer_end

.sound_rando_voice_083:
chan_setbank 10
chan_setinstr 3
chan_setlayer 0, .layer_rando_voice_083
chan_end

.layer_rando_voice_083:
layer_note1_long 39, 204, 127
layer_end

.sound_rando_voice_084:
chan_setbank 10
chan_setinstr 4
chan_setlayer 0, .layer_rando_voice_084
chan_end

.layer_rando_voice_084:
layer_note1_long 39, 116, 127
layer_end

.sound_rando_voice_085:
chan_setbank 10
chan_setinstr 5
chan_setlayer 0, .layer_rando_voice_085
chan_end

.layer_rando_voice_085:
layer_note1_long 39, 142, 127
layer_end

.sound_rando_voice_086:
chan_setbank 10
chan_setinstr 6
chan_setlayer 0, .layer_rando_voice_086
chan_end

.layer_rando_voice_086:
layer_note1_long 39, 128, 127
layer_end

.sound_rando_voice_087:
chan_setbank 10
chan_setinstr 7
chan_setlayer 0, .layer_rando_voice_087
chan_end

.layer_rando_voice_087:
layer_note1_long 39, 138, 127
layer_end

.sound_rando_voice_088:
chan_setbank 11
chan_setinstr 0
chan_setlayer 0, .layer_rando_voice_088
chan_end

.layer_rando_voice_088:
layer_note1_long 39, 206, 127
layer_end

.sound_rando_voice_089:
chan_setbank 11
chan_setinstr 1
chan_setlayer 0, .layer_rando_voice_089
chan_end

.layer_rando_voice_089:
layer_note1_long 39, 110, 127
layer_end

.sound_rando_voice_090:
chan_setbank 11
chan_setinstr 2
chan_setlayer 0, .layer_rando_voice_090
chan_end

.layer_rando_voice_090:
layer_note1_long 39, 204, 127
layer_end

.sound_rando_voice_091:
chan_setbank 11
chan_setinstr 3
chan_setlayer 0, .layer_rando_voice_091
chan_end

.layer_rando_voice_091:
layer_note1_long 39, 108, 127
layer_end

.sound_rando_voice_092:
chan_setbank 11
chan_setinstr 4
chan_setlayer 0, .layer_rando_voice_092
chan_end

.layer_rando_voice_092:
layer_note1_long 39, 118, 127
layer_end

.sound_rando_voice_093:
chan_setbank 11
chan_setinstr 5
chan_setlayer 0, .layer_rando_voice_093
chan_end

.layer_rando_voice_093:
layer_note1_long 39, 84, 127
layer_end

.sound_rando_voice_094:
chan_setbank 11
chan_setinstr 6
chan_setlayer 0, .layer_rando_voice_094
chan_end

.layer_rando_voice_094:
layer_note1_long 39, 110, 127
layer_end

.sound_rando_voice_095:
chan_setbank 11
chan_setinstr 7
chan_setlayer 0, .layer_rando_voice_095
chan_end

.layer_rando_voice_095:
layer_note1_long 39, 138, 127
layer_end

.sound_rando_voice_096:
chan_setbank 12
chan_setinstr 0
chan_setlayer 0, .layer_rando_voice_096
chan_end

.layer_rando_voice_096:
layer_note1_long 39, 216, 127
layer_end

.sound_rando_voice_097:
chan_setbank 12
chan_setinstr 1
chan_setlayer 0, .layer_rando_voice_097
chan_end

.layer_rando_voice_097:
layer_note1_long 39, 192, 127
layer_end

.sound_rando_voice_098:
chan_setbank 12
chan_setinstr 2
chan_setlayer 0, .layer_rando_voice_098
chan_end

.layer_rando_voice_098:
layer_note1_long 39, 128, 127
layer_end

.sound_rando_voice_099:
chan_setbank 12
chan_setinstr 3
chan_setlayer 0, .layer_rando_voice_099
chan_end

.layer_rando_voice_099:
layer_note1_long 39, 116, 127
layer_end

.sound_rando_voice_100:
chan_setbank 12
chan_setinstr 4
chan_setlayer 0, .layer_rando_voice_100
chan_end

.layer_rando_voice_100:
layer_note1_long 39, 196, 127
layer_end

.sound_rando_voice_101:
chan_setbank 12
chan_setinstr 5
chan_setlayer 0, .layer_rando_voice_101
chan_end

.layer_rando_voice_101:
layer_note1_long 39, 112, 127
layer_end

.sound_rando_voice_102:
chan_setbank 12
chan_setinstr 6
chan_setlayer 0, .layer_rando_voice_102
chan_end

.layer_rando_voice_102:
layer_note1_long 39, 110, 127
layer_end

.sound_rando_voice_103:
chan_setbank 12
chan_setinstr 7
chan_setlayer 0, .layer_rando_voice_103
chan_end

.layer_rando_voice_103:
layer_note1_long 39, 120, 127
layer_end

.sound_rando_voice_104:
chan_setbank 13
chan_setinstr 0
chan_setlayer 0, .layer_rando_voice_104
chan_end

.layer_rando_voice_104:
layer_note1_long 39, 186, 127
layer_end

.sound_rando_voice_105:
chan_setbank 13
chan_setinstr 1
chan_setlayer 0, .layer_rando_voice_105
chan_end

.layer_rando_voice_105:
layer_note1_long 39, 206, 127
layer_end

.sound_rando_voice_106:
chan_setbank 13
chan_setinstr 2
chan_setlayer 0, .layer_rando_voice_106
chan_end

.layer_rando_voice_106:
layer_note1_long 39, 202, 127
layer_end

.sound_rando_voice_107:
chan_setbank 13
chan_setinstr 3
chan_setlayer 0, .layer_rando_voice_107
chan_end

.layer_rando_voice_107:
layer_note1_long 39, 182, 127
layer_end

.sound_rando_voice_108:
chan_setbank 13
chan_setinstr 4
chan_setlayer 0, .layer_rando_voice_108
chan_end

.layer_rando_voice_108:
layer_note1_long 39, 84, 127
layer_end

.sound_rando_voice_109:
chan_setbank 13
chan_setinstr 5
chan_setlayer 0, .layer_rando_voice_109
chan_end

.layer_rando_voice_109:
layer_note1_long 39, 136, 127
layer_end

.sound_rando_voice_110:
chan_setbank 13
chan_setinstr 6
chan_setlayer 0, .layer_rando_voice_110
chan_end

.layer_rando_voice_110:
layer_note1_long 39, 204, 127
layer_end

.sound_rando_voice_111:
chan_setbank 13
chan_setinstr 7
chan_setlayer 0, .layer_rando_voice_111
chan_end

.layer_rando_voice_111:
layer_note1_long 39, 194, 127
layer_end

.sound_rando_voice_112:
chan_setbank 14
chan_setinstr 0
chan_setlayer 0, .layer_rando_voice_112
chan_end

.layer_rando_voice_112:
layer_note1_long 39, 206, 127
layer_end

.sound_rando_voice_113:
chan_setbank 14
chan_setinstr 1
chan_setlayer 0, .layer_rando_voice_113
chan_end

.layer_rando_voice_113:
layer_note1_long 39, 214, 127
layer_end

.sound_rando_voice_114:
chan_setbank 14
chan_setinstr 2
chan_setlayer 0, .layer_rando_voice_114
chan_end

.layer_rando_voice_114:
layer_note1_long 39, 190, 127
layer_end

.sound_rando_voice_115:
chan_setbank 14
chan_setinstr 3
chan_setlayer 0, .layer_rando_voice_115
chan_end

.layer_rando_voice_115:
layer_note1_long 39, 88, 127
layer_end

.sound_rando_voice_116:
chan_setbank 14
chan_setinstr 4
chan_setlayer 0, .layer_rando_voice_116
chan_end

.layer_rando_voice_116:
layer_note1_long 39, 108, 127
layer_end

.sound_rando_voice_117:
chan_setbank 14
chan_setinstr 5
chan_setlayer 0, .layer_rando_voice_117
chan_end

.layer_rando_voice_117:
layer_note1_long 39, 92, 127
layer_end

.sound_rando_voice_118:
chan_setbank 14
chan_setinstr 6
chan_setlayer 0, .layer_rando_voice_118
chan_end

.layer_rando_voice_118:
layer_note1_long 39, 110, 127
layer_end

.sound_rando_voice_119:
chan_setbank 14
chan_setinstr 7
chan_setlayer 0, .layer_rando_voice_119
chan_end

.layer_rando_voice_119:
layer_note1_long 39, 106, 127
layer_end
